# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: edelanno <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/11/18 16:36:25 by edelanno          #+#    #+#              #
#    Updated: 2024/11/18 16:36:26 by edelanno         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ftprintf
CC = cc 
CFLAGS = -Wall -Wextra -Werror -I ./
SRC = ft_printf.c ft_printf2.c
OBJ = $(SRC:.c=.o)

all : $(NAME)

$(NAME) : $(OBJ)
	ar rcs $(NAME) $(OBJ)

%.o : %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean : 
	rm -f $(OBJ)

fclean :
	rm -f $(NAME)

re : fclean all